# Specifying Compilers 
CXX = g++

# Compilation Options
CXXFLAGS = -std=c++11
TESTFLAGs = -std=c++11 -Wall -Werror

# Target executable file name
TARGET = my_build_system.out

# source file
SRC = gs.cpp

# Rule: Generate executable file
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

# Clean up build files
clean:
	rm -f $(TARGET)

#Clean up .vtk files generated by the simulation
cleanvtk:
	rm -f $(wildcard *.vtk)

#Compile the test version of gs.cpp
# test:
