# Specifying Compilers
CXX = g++

# Compilation Options
CXXFLAGS = -std=c++11
TESTFLAGs = -std=c++11 -Wall -Werror

# Target executable file name
TARGET = sim.out

# source file
SRC = gs.cpp

# Rule: Generate executable file
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

# Clean up build files
.PHONY: clean
clean:
	rm -f $(TARGET)
	rm -f $(wildcard *.vtk)

#Clean up .vtk files generated by the simulation
.PHONY: cleanvtk
cleanvtk:
	rm -f $(wildcard *.vtk)

#Compile the test version of gs.cpp
# test:
