name: C++ Test Build System and CI
# Trigger action
on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*' 
# Specify latest version of ubuntu
jobs:
  build:
    runs-on: ubuntu-latest  
    # Pull repository's code to GitHub
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      # Install required packages
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make  
      # Create build directory, configure and compile google test
      - name: Setup Google Test
        run: |
          git clone https://github.com/google/googletest.git
          mkdir -p googletest/build
          cd googletest
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build  

      - name: Configure and Build Project with CMake
        run: |
          cmake -S . -B build -DGTEST_ROOT=googletest 
          cmake --build build 

      - name: Run tests and save result
        run: |
          cd build
          ctest --output-on-failure > test_result.log
        shell: bash
  
      - name: Upload test result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: build/test_result.log